//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG1.ComedorGeo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alimento
    {
        public Alimento()
        {
            this.DetalleAlimento = new HashSet<DetalleAlimento>();
            this.Menu = new HashSet<Menu>();
        }
    
        public long id { get; set; }
        public string NombreAlimento { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public long itTipo { get; set; }
        public long itTipoAlimento { get; set; }
    
        public virtual Tipo Tipo { get; set; }
        public virtual TipoAlimento TipoAlimento { get; set; }
        public virtual ICollection<DetalleAlimento> DetalleAlimento { get; set; }
        public virtual ICollection<Menu> Menu { get; set; }
    }
}
