//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG1.ComedorGeo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleProgramacion
    {
        public DetalleProgramacion()
        {
            this.DetalleEstadoServicio = new HashSet<DetalleEstadoServicio>();
        }
    
        public long idEmpleado { get; set; }
        public long idProgramacion { get; set; }
        public long idEstado { get; set; }
    
        public virtual ICollection<DetalleEstadoServicio> DetalleEstadoServicio { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Programacion Programacion { get; set; }
    }
}
