//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG1.ComedorGeo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleEstadoServicio
    {
        public long idEmpleado { get; set; }
        public long idProgramacion { get; set; }
        public long idOrdenServicio { get; set; }
        public long idEstado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual OrdenServicio OrdenServicio { get; set; }
        public virtual DetalleProgramacion DetalleProgramacion { get; set; }
    }
}
