//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG1.ComedorGeo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleAlimento
    {
        public long idAlimento { get; set; }
        public long idIngrediente { get; set; }
        public double Porcion { get; set; }
        public Nullable<double> TotalCalorias { get; set; }
    
        public virtual Alimento Alimento { get; set; }
        public virtual Ingrediente Ingrediente { get; set; }
    }
}
