//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG1.ComedorGeo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.DetalleEstado = new HashSet<DetalleEstado>();
            this.DetalleProgramacion = new HashSet<DetalleProgramacion>();
        }
    
        public long id { get; set; }
        public long idEmpresa { get; set; }
        public long idCargo { get; set; }
        public long idArea { get; set; }
        public long idCentroCosto { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public long idTurno { get; set; }
        public long idUsuario { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual CentroCosto CentroCosto { get; set; }
        public virtual ICollection<DetalleEstado> DetalleEstado { get; set; }
        public virtual ICollection<DetalleProgramacion> DetalleProgramacion { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Turno Turno { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
