//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG1.ComedorGeo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.Empleado = new HashSet<Empleado>();
            this.RepresentanteLegal = new HashSet<RepresentanteLegal>();
        }
    
        public long id { get; set; }
        public string RazonSocial { get; set; }
        public string Nit { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public long idRubro { get; set; }
        public long idTipo { get; set; }
    
        public virtual ICollection<Empleado> Empleado { get; set; }
        public virtual Rubro Rubro { get; set; }
        public virtual TipoEmpresa TipoEmpresa { get; set; }
        public virtual ICollection<RepresentanteLegal> RepresentanteLegal { get; set; }
    }
}
