//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG1.ComedorGeo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.OrdenServicio = new HashSet<OrdenServicio>();
        }
    
        public long id { get; set; }
        public System.DateTime FechaMenu { get; set; }
        public long idAlimento { get; set; }
    
        public virtual Alimento Alimento { get; set; }
        public virtual ICollection<OrdenServicio> OrdenServicio { get; set; }
    }
}
