//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG1.ComedorGeo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenServicio
    {
        public OrdenServicio()
        {
            this.DetalleEstadoServicio = new HashSet<DetalleEstadoServicio>();
        }
    
        public long id { get; set; }
        public string Observacion { get; set; }
        public long idMenu { get; set; }
    
        public virtual ICollection<DetalleEstadoServicio> DetalleEstadoServicio { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
