//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG1.ComedorGeo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBResumenAlimentacion
    {
        public long id { get; set; }
        public System.DateTime FechaAlimentacion { get; set; }
        public long CodigoEmpleado { get; set; }
        public string NombreEmpleado { get; set; }
        public string Cargo { get; set; }
        public string CentroCosto { get; set; }
        public string Area { get; set; }
        public string TipoMenu { get; set; }
        public string Plato { get; set; }
        public long CaloriasPlato { get; set; }
        public string Bebida { get; set; }
        public long CaloriasBebida { get; set; }
        public string Postre { get; set; }
        public long CaloriasPostre { get; set; }
        public double TotalPrecio { get; set; }
    }
}
