//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG1.ComedorGeo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDetalleProgramacion
    {
        public long idEmpleado { get; set; }
        public string NombreCompleto { get; set; }
        public string NombreArea { get; set; }
        public long idProgramacion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public long idEstado { get; set; }
        public string NombreEstado { get; set; }
    }
}
