//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG1.ComedorGeo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEmpleado
    {
        public long id { get; set; }
        public string NombreCompleto { get; set; }
        public long idEmpresa { get; set; }
        public string RazonSocial { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public long idCargo { get; set; }
        public string NombreCargo { get; set; }
        public long idArea { get; set; }
        public string NombreArea { get; set; }
        public long idCentroCosto { get; set; }
        public string NombreCentroCosto { get; set; }
        public long idTurno { get; set; }
        public string NombreTurno { get; set; }
        public long idUsuario { get; set; }
        public string NombreUsuario { get; set; }
    }
}
